---

title: "awesome YOGIBO!"
	
date: 2020-11-08

---

author: YOGIBO believer
email: your-email@domain.com
description: > This page is about YOGIBO. You will believe YOGIBO.
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
